---
- name: Install Prometheus Node Exporter on Ubuntu VMs
  hosts: all
  become: yes
  vars:
    node_exporter_version: "1.2.2"  # Change this to the desired version of Node Exporter
    username: "your_username"      # Change this to your username for connecting to VMs
    password: "your_password"      # Change this to your password for connecting to VMs
  tasks:
    - name: Ensure dependencies are installed
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - wget
        - curl

    - name: Download Node Exporter binary
      get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
        dest: /tmp/node_exporter.tar.gz
        validate_certs: no

    - name: Extract Node Exporter
      ansible.builtin.unarchive:
        src: /tmp/node_exporter.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: Move Node Exporter binary to /usr/local/bin
      ansible.builtin.copy:
        src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
        dest: /usr/local/bin/node_exporter
        mode: '0755'

    - name: Create system user for Node Exporter
      ansible.builtin.user:
        name: node_exporter
        system: yes

    - name: Create systemd service file
      ansible.builtin.template:
        src: node_exporter.service.j2
        dest: /etc/systemd/system/node_exporter.service
      notify: restart node exporter

    - name: Start Node Exporter service
      ansible.builtin.service:
        name: node_exporter
        state: started
        enabled: yes

  handlers:
    - name: restart node exporter
      ansible.builtin.service:
        name: node_exporter
        state: restarted
